<a href="https://colab.research.google.com/github/wizard339/NLP_MISIS/blob/main/2_week/calc_hidden_state_example.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

→ Дан текст (для задания 8.1): “мама мыла”

→ Веса для слов: мама = [0.2, 0.5, 0.8]; мыла = [0.5, 0.6, -0.3]

→ Матрица весов Wh = [[0.4, 0.6, 0.9], [-0.2, 0.5, 0.1], [0.2, 0.1, -0.7]]

→ Матрица весов We = [[0.3, -0.1, 0.4], [0.2, -0.7, 0.4], [0.3, 0.2, 0.8]]

→ Вектор b = [0.9, 0.4, -0.8]

In [2]:
text = 'мама мыла'

In [3]:
e1 = np.array([0.2, 0.5, 0.8])
e1

array([0.2, 0.5, 0.8])

In [4]:
e2 = np.array([0.5, 0.6, -0.3])
e2

array([ 0.5,  0.6, -0.3])

In [5]:
Wh = np.array([[0.4, 0.6, 0.9], [-0.2, 0.5, 0.1], [0.2, 0.1, -0.7]])
Wh

array([[ 0.4,  0.6,  0.9],
       [-0.2,  0.5,  0.1],
       [ 0.2,  0.1, -0.7]])

In [6]:
We = np.array([[0.3, -0.1, 0.4], [0.2, -0.7, 0.4], [0.3, 0.2, 0.8]])
We

array([[ 0.3, -0.1,  0.4],
       [ 0.2, -0.7,  0.4],
       [ 0.3,  0.2,  0.8]])

In [7]:
b = np.array([0.9, 0.4, -0.8])
b

array([ 0.9,  0.4, -0.8])

In [8]:
def sigmoid(x):
  return 1 / (1 + np.exp(-x))

assert sigmoid(0.458) == 0.61253961344091512

In [9]:
h0 = np.zeros(3)
h0

array([0., 0., 0.])

In [10]:
h1 = sigmoid(np.dot(Wh, h0) + np.dot(We, e1) + b)
h1

array([0.77381857, 0.60108788, 0.5       ])

In [11]:
h2 = sigmoid(np.dot(Wh, h1) + np.dot(We, e2) + b)
h2

array([0.8797622 , 0.53886649, 0.28799794])

In [12]:
np.round(h2, 2)

array([0.88, 0.54, 0.29])